import SwiftUI
import SpriteKit

// MARK: - Shared layout constants (must match SmokeScene)

enum IncenseLayout {
    static let holderHeight: CGFloat = 50
    static let centerStickHeight: CGFloat = 200
    static let sideStickHeight: CGFloat = 180
    static let stickSpacing: CGFloat = 37  // HStack spacing between stick edges
    static let stickFrameWidth: CGFloat = 20
    static let ashFrameWidth: CGFloat = 92
    static let stickWidth: CGFloat = 5
    static let canvasHeight: CGFloat = 340

    /// Fraction of original height remaining as stick burns (0.08 = 8% stub left)
    static func burnFraction(progress: Double) -> CGFloat {
        CGFloat(1.0 - progress * 0.92)
    }
}

enum AshMath {
    static func clamp(_ value: CGFloat, min lower: CGFloat, max upper: CGFloat) -> CGFloat {
        max(lower, min(upper, value))
    }

    static func smoothstep(_ value: Double, start: Double, end: Double) -> CGFloat {
        guard end > start else { return value >= end ? 1 : 0 }
        let normalized = clamp(CGFloat((value - start) / (end - start)), min: 0, max: 1)
        return normalized * normalized * (3 - 2 * normalized)
    }

    static func lerp(_ start: CGFloat, _ end: CGFloat, _ t: CGFloat) -> CGFloat {
        start + (end - start) * t
    }
}

// MARK: - Ash seed

/// Per-stick structural parameters for the chain-integration ash model.
/// The ash path is generated by integrating a tangent-angle function along
/// the arc from root (stick attachment) to tip, producing the same shape
/// a physical chain would adopt as the tip traces its growth trajectory.
struct AshSeed {
    /// -1 = curls left, +1 = curls right
    let curlDirection: CGFloat
    /// Burn-progress offset before ash starts appearing
    let growthDelay: Double
    /// Fraction of total arc that forms the straight hanging stem [0.10, 0.22]
    let stemFraction: CGFloat
    /// Fraction of total arc occupied by the main loop circle [0.40, 0.60]
    let loopFraction: CGFloat
    /// Total angle the loop sweeps in radians; ~2π = full circle [1.5π, 2.0π]
    let loopSweep: CGFloat
    /// Angle-distribution exponent. 1.0 = circular, >1 = teardrop (more arc near base)
    let loopPace: CGFloat
    /// Governs how quickly the tail returns toward vertical after the loop [0.6, 1.4]
    let tailGravity: CGFloat
    let strokeWidth: CGFloat

    /// Left stick: curls left, gentle teardrop loop
    static let left = AshSeed(
        curlDirection: -1,
        growthDelay: 0.03,
        stemFraction: 0.17,
        loopFraction: 0.56,
        loopSweep: .pi * 1.85,
        loopPace: 1.30,
        tailGravity: 1.0,
        strokeWidth: 2.0
    )

    /// Center stick: curls right, pronounced teardrop loop, tighter tail return
    static let center = AshSeed(
        curlDirection: 1,
        growthDelay: 0.01,
        stemFraction: 0.13,
        loopFraction: 0.52,
        loopSweep: .pi * 1.88,
        loopPace: 1.65,
        tailGravity: 0.80,
        strokeWidth: 2.1
    )

    /// Right stick: curls right, near-circular loop, longer stem
    static let right = AshSeed(
        curlDirection: 1,
        growthDelay: 0.05,
        stemFraction: 0.20,
        loopFraction: 0.56,
        loopSweep: .pi * 1.92,
        loopPace: 1.10,
        tailGravity: 1.15,
        strokeWidth: 1.95
    )
}

// MARK: - AshTrailShape

/// Draws the burned-away portion of an incense stick as a hanging coiled ash trail.
///
/// **Chain integration model**: the ash path is the growth trajectory of the burning tip.
/// At each infinitesimal arc step the tangent angle is sampled from a shaped function,
/// then integrated (dx = sin θ · dl, dy = cos θ · dl) to produce absolute positions.
/// Because each older segment was once the tip, old ash naturally follows wherever the
/// newer ash ahead of it leads — exactly the physical chain behaviour.
struct AshTrailShape: Shape {
    let burnProgress: Double
    let fullHeight: CGFloat
    let seed: AshSeed

    func path(in rect: CGRect) -> Path {
        let pts = ashPoints(in: rect)
        guard pts.count >= 2 else { return Path() }

        var p = Path()
        p.move(to: pts[0])
        let n = pts.count
        for i in 1..<n {
            if i < n - 1 {
                let mid = CGPoint(
                    x: (pts[i].x + pts[i + 1].x) * 0.5,
                    y: (pts[i].y + pts[i + 1].y) * 0.5
                )
                p.addQuadCurve(to: mid, control: pts[i])
            } else {
                p.addLine(to: pts[i])
            }
        }
        return p
    }

    // MARK: - Chain integration

    /// Tangent angle at normalized arc position s ∈ [0, 1] (0 = root, 1 = tip).
    ///
    /// Convention: angle = 0 → pointing straight down (+y).
    /// Positive values turn toward `seed.curlDirection` (sideways → upward → loop).
    /// The returned value already carries the curlDirection sign, so callers integrate with
    ///   dx = sin(angle) · dl
    ///   dy = cos(angle) · dl   (screen-space: y increases downward)
    private func tangentAngle(at s: CGFloat, loopProgress: CGFloat, tailProgress: CGFloat) -> CGFloat {
        let loopEnd = seed.stemFraction + seed.loopFraction

        if s <= seed.stemFraction {
            // Straight stem: near-vertical with tiny chain-tension lean toward curl
            let t = s / max(seed.stemFraction, 0.001)
            return seed.curlDirection * 0.06 * t * loopProgress

        } else if s <= loopEnd {
            // Main loop arc: angle sweeps 0 → loopSweep.
            // loopPace > 1 distributes more arc near angle≈0 (going downward first),
            // creating a teardrop shape instead of a symmetric circle.
            let t = (s - seed.stemFraction) / max(seed.loopFraction, 0.001)
            return seed.curlDirection * seed.loopSweep * loopProgress * pow(t, seed.loopPace)

        } else {
            // Tail: transitions from loop exit angle back toward near-vertical hanging.
            let t = (s - loopEnd) / max(1.0 - loopEnd, 0.001)
            let exitAngle = seed.curlDirection * seed.loopSweep * loopProgress
            // Droop target: slight outward lean from vertical, scaled by tailGravity
            let droopAngle = seed.curlDirection * .pi * 0.08 * seed.tailGravity * tailProgress
            // easeOut: quick initial rotation, then settles into the droop angle
            let eased = 1 - pow(max(0, 1 - t), 2)
            return AshMath.lerp(exitAngle, droopAngle, eased)
        }
    }

    /// Builds the list of arc points by walking the tangent-angle field.
    /// Each step moves dl along the direction given by tangentAngle(s).
    private func ashPoints(in rect: CGRect) -> [CGPoint] {
        let raw = max(0, burnProgress - seed.growthDelay)
        guard raw > 0.01 else { return [] }
        let effectiveBP = raw / max(0.01, 1.0 - seed.growthDelay)

        // Total visible arc length grows non-linearly with burn progress
        let burnedLength = fullHeight * 0.92 * CGFloat(effectiveBP)
        let grow = AshMath.smoothstep(effectiveBP, start: 0.04, end: 0.82)
        let totalLength = burnedLength * AshMath.lerp(0.06, 0.94, grow)
        guard totalLength > 3 else { return [] }

        // Loop forms gradually; tail activates later
        let loopP = AshMath.smoothstep(effectiveBP, start: 0.14, end: 0.82)
        let tailP = AshMath.smoothstep(effectiveBP, start: 0.50, end: 0.96)

        let numSteps = max(6, Int(totalLength / 2.5))
        let dl = totalLength / CGFloat(numSteps)

        var pts = [CGPoint]()
        var x = rect.midX
        var y: CGFloat = 0
        pts.append(CGPoint(x: x, y: y))

        for i in 1...numSteps {
            let s = CGFloat(i) / CGFloat(numSteps)
            let angle = tangentAngle(at: s, loopProgress: loopP, tailProgress: tailP)
            x += sin(angle) * dl
            y += cos(angle) * dl
            pts.append(CGPoint(x: x, y: y))
        }

        return pts
    }
}

// MARK: - AshTrailView

/// Renders the progressive ash trail for one incense stick and animates
/// it falling into the holder when burning completes. Resets automatically
/// when burnProgress returns to 0 (after session reset).
struct AshTrailView: View {
    let burnProgress: Double
    let fullHeight: CGFloat
    let seed: AshSeed
    let isComplete: Bool

    @State private var fallOffset: CGFloat = 0
    @State private var ashOpacity: Double = 1

    private var burnOffset: CGFloat {
        // Keep the ash root attached to the visual burning tip as the stick shrinks.
        fullHeight * (1 - IncenseLayout.burnFraction(progress: burnProgress))
    }

    var body: some View {
        AshTrailShape(
            burnProgress: burnProgress,
            fullHeight: fullHeight,
            seed: seed
        )
        .stroke(
            LinearGradient(
                colors: [
                    Color(white: 0.82, opacity: 0.14),
                    Color(white: 0.70, opacity: 0.44),
                    Color(white: 0.56, opacity: 0.74),
                ],
                startPoint: .top,
                endPoint: .bottom
            ),
            style: StrokeStyle(lineWidth: seed.strokeWidth, lineCap: .round, lineJoin: .round)
        )
        .frame(width: IncenseLayout.ashFrameWidth, height: fullHeight, alignment: .top)
        .offset(y: burnOffset + fallOffset)
        .opacity(ashOpacity)
        .allowsHitTesting(false)
        .onChange(of: isComplete) { _, complete in
            if complete {
                withAnimation(.easeIn(duration: 1.3).delay(0.15)) {
                    fallOffset = fullHeight * 0.55
                    ashOpacity = 0
                }
            } else {
                fallOffset = 0
                ashOpacity = 1
            }
        }
    }
}

// MARK: - IncenseStickView

struct IncenseStickView: View {
    let isLit: Bool
    let fullHeight: CGFloat
    let progress: Double
    let ashSeed: AshSeed

    private var burnFraction: CGFloat {
        IncenseLayout.burnFraction(progress: progress)
    }

    var body: some View {
        ZStack(alignment: .top) {
            // Stick body — scales from the bottom (tip burns away from top)
            RoundedRectangle(cornerRadius: 2.5)
                .fill(Color.white.opacity(0.82))
                .frame(width: IncenseLayout.stickWidth)
                .scaleEffect(y: burnFraction, anchor: .bottom)
                .shadow(color: .white.opacity(0.6), radius: 3)
                .shadow(color: .white.opacity(0.25), radius: 7)

            // Ash trail overlaying the burned-away portion of the stick
            if isLit && progress > 0.01 {
                AshTrailView(
                    burnProgress: progress,
                    fullHeight: fullHeight,
                    seed: ashSeed,
                    isComplete: progress >= 1.0
                )
            }

            // Flame glow at the current burning tip — cold white neon style
            if isLit && progress < 1.0 {
                ZStack {
                    Circle()
                        .fill(Color.white.opacity(0.12))
                        .frame(width: 22, height: 22)
                        .blur(radius: 7)
                    Circle()
                        .fill(
                            RadialGradient(
                                colors: [.white, Color(white: 0.88, opacity: 0.85)],
                                center: .center,
                                startRadius: 0,
                                endRadius: 5
                            )
                        )
                        .frame(width: 7, height: 7)
                        .shadow(color: .white.opacity(0.9), radius: 6)
                        .shadow(color: .white.opacity(0.5), radius: 10)
                }
                // Position flame at the visual top of the shrinking stick
                .offset(y: fullHeight * (1.0 - burnFraction))
            }
        }
        .frame(width: IncenseLayout.stickFrameWidth, height: fullHeight)
    }
}

// MARK: - IncenseHolderView

struct IncenseHolderView: View {
    var body: some View {
        VStack(spacing: 0) {
            // Tray with three stick holes — glowing neon stroke
            ZStack {
                RoundedRectangle(cornerRadius: 8)
                    .stroke(Color.white.opacity(0.65), lineWidth: 1.5)
                    .frame(width: 130, height: 16)
                    .shadow(color: .white.opacity(0.75), radius: 5)
                    .shadow(color: .white.opacity(0.25), radius: 12)

                HStack(spacing: IncenseLayout.stickSpacing) {
                    ForEach(0..<3, id: \.self) { _ in
                        Circle()
                            .fill(Color.black)
                            .overlay(
                                Circle().stroke(Color.white.opacity(0.35), lineWidth: 1)
                            )
                            .frame(width: 7, height: 7)
                    }
                }
            }

            // Narrow neck — thin glowing connector
            Capsule()
                .fill(Color.white.opacity(0.4))
                .frame(width: 28, height: 8)
                .shadow(color: .white.opacity(0.6), radius: 4)

            // Pedestal base — glowing neon stroke
            RoundedRectangle(cornerRadius: 8)
                .stroke(Color.white.opacity(0.65), lineWidth: 1.5)
                .frame(width: 140, height: 26)
                .shadow(color: .white.opacity(0.75), radius: 6)
                .shadow(color: .white.opacity(0.25), radius: 14)
        }
        .frame(height: IncenseLayout.holderHeight)
    }
}

// MARK: - IncenseSmokeView

struct IncenseSmokeView: View {
    @Environment(BurnSession.self) private var session
    @Environment(TiltManager.self) private var tiltManager

    @State private var scene: SmokeScene = {
        let s = SmokeScene(size: CGSize(width: 300, height: IncenseLayout.canvasHeight))
        s.backgroundColor = .clear
        s.anchorPoint = CGPoint(x: 0.5, y: 0)
        s.scaleMode = .resizeFill
        return s
    }()

    var body: some View {
        SpriteView(scene: scene, options: [.allowsTransparency])
            .allowsHitTesting(false)
            .onChange(of: session.litSticks) { old, new in
                for i in 0..<new.count where !old[i] && new[i] {
                    scene.lightStick(at: i)
                }
            }
            .onChange(of: session.progress) { _, p in
                scene.updateProgress(p)
            }
            .onChange(of: session.state) { _, s in
                if s == .complete { scene.extinguishAll() }
            }
            // Tilt-reactive smoke: pipe filtered roll/pitch into particle system
            .onChange(of: tiltManager.roll) { _, roll in
                scene.updateTilt(roll: roll, pitch: tiltManager.pitch)
            }
    }
}

// MARK: - IncenseCanvasView

struct IncenseCanvasView: View {
    @Environment(BurnSession.self) private var session

    var body: some View {
        ZStack(alignment: .bottom) {
            // Smoke layer (transparent SpriteKit overlay)
            IncenseSmokeView()

            // Sticks + holder aligned to the bottom
            VStack(spacing: 0) {
                HStack(alignment: .bottom, spacing: IncenseLayout.stickSpacing) {
                    // Left stick – larger outward loop
                    IncenseStickView(
                        isLit: session.litSticks[0],
                        fullHeight: IncenseLayout.sideStickHeight,
                        progress: session.progress,
                        ashSeed: .left
                    )

                    // Center stick – tighter central hanging loop; tap/long-press to ignite
                    IncenseStickView(
                        isLit: session.litSticks[1],
                        fullHeight: IncenseLayout.centerStickHeight,
                        progress: session.progress,
                        ashSeed: .center
                    )
                    .contentShape(Rectangle())
                    .onTapGesture {
                        Task { await session.ignite() }
                    }
                    .gesture(
                        LongPressGesture(minimumDuration: 0.8)
                            .onEnded { _ in
                                Task { await session.ignite() }
                            }
                    )
                    .disabled(![.idle, .composing].contains(session.state))

                    // Right stick – larger outward loop
                    IncenseStickView(
                        isLit: session.litSticks[2],
                        fullHeight: IncenseLayout.sideStickHeight,
                        progress: session.progress,
                        ashSeed: .right
                    )
                }

                IncenseHolderView()
            }
        }
        .frame(height: IncenseLayout.canvasHeight)
    }
}
